export const data=[
    [   "Acetic Acid",
        "Acetic Acid",
        "60.05",
        "C2H4O2",
        "64-19-7",
        "-.17",
        "Yes",
        "1",
        "2",
        "https://pubchem.ncbi.nlm.nih.gov/image/imgsrv.fcgi?cid=176&t=l",
        ["Carboxilic Acid"],
        ["Is the scent and flavor of vinegar. Used as a flavor enhancer, pickling agent, and solvent"],
        ["Typically called glacial acetic acid"],
        ["Called glacial acetic acid because of high freezing point.",
            "When it freezes, it looks like ice, hence glacial"],
        ["CHE327"]
    ],
    [   "Acetone",
        "Propan-2-one",
        "58.08",
        "C3H6O1",
        "67-64-1",
        "-.1",
        "Yes",
        "0",
        "1",
        "https://pubchem.ncbi.nlm.nih.gov/image/imgsrv.fcgi?cid=180&t=l",
        ["Ketone"],
        ["Found in nail polish, nail polish remover, markers, airplane glue solvent, fabric cement, cleaning fluids, paint, varnish, and lacquer. Used as a solvent to clean & dry. Flammable."],
        ['used as a nail remover, paint remover - known as "spirit of Saturn"'],
        ["Discovered by alchemists in the MIddle Ages",
            "Jean Baptiste Dumas and Justus Von Leibig determined the chemical structure"],
        ["CHE327"]
    ],
    [   "Chloroform",
        "Trichloromethane",
        "119.37",
        "C1H1Cl3",
        "67-66-3",
        "2.3 or 1.97",
        "Partially",
        "0",
        "0",
        "https://pubchem.ncbi.nlm.nih.gov/image/imgsrv.fcgi?cid=6212&t=l",
        ["Alkyl Halide"],
        ["Known as something you put on a rag to knock people out, chloroform is also a solvent for many molecules (although not very soluble in water)."],
        ["-colorless liquid that evaporates into a gas  CCl3"],
        ["-used as an anesthetic during childbirth and surgery (replaced ether) ",
            ],
        ["CHE327"]
    ]
]


export const headers=[
    "IUPAC Name",
    "MW g/mol",
    "Formula",
    "CAS Number",
    "logP?",
    "Soluble?",
    "H Donors",
    "H Acceptors",
    "Functional Groups",
    "What it Does",
    "Notes",
    "Fun Facts"
]

export const classes=[
    "CHE121",
    "CHE122",
    "CHE202",
    "CHE225",
    "CHE326",
    "CHE327",
    "CHE334",
    "BIO328"
]